// Package codegen renders a resolved plan into gofmt-compatible Go source.
//
// Output is deterministic: the same input always produces byte-identical
// source. Imports and local variable names are derived from the graph, with
// numeric suffixes assigned in a stable order to resolve conflicts.
package codegen

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/Xwudao/loom/internal/model"
	"github.com/Xwudao/loom/internal/resolve"

	"golang.org/x/tools/go/packages"
)

// Options carries the framework types codegen needs to reference.
type Options struct {
	// LoomPkg is the loom package, used for loom.NewLifecycle.
	LoomPkg *types.Package
	// LifecyclePtr is *loom.Lifecycle.
	LifecyclePtr types.Type
	// Cleanup is loom.Cleanup.
	Cleanup types.Type
	// Context is context.Context.
	Context types.Type
	// ErrorsPkg is the standard library errors package, used for errors.Join.
	ErrorsPkg *types.Package
}

// File accumulates the generated functions for one package.
type File struct {
	pkg     *packages.Package
	opts    Options
	imports *importSet
	funcs   []string
	head    string
}

// NewFile returns an empty generated file for pkg under a leading comment.
func NewFile(pkg *packages.Package, opts Options, header string) *File {
	return &File{pkg: pkg, opts: opts, imports: newImportSet(), head: header}
}

// AddGraph renders one graph into the file.
func (f *File) AddGraph(g *model.Graph, plan *resolve.Plan) error {
	f.collect(g, plan)
	w := &graphWriter{
		f:        f,
		g:        g,
		plan:     plan,
		varNames: map[*resolve.Step]string{},
	}
	w.names = newNamer()
	w.names.reserve("lifecycle", "err", g.Name)
	if g.WithCtx {
		w.names.reserve("ctx")
	}
	w.names.reserve(f.imports.aliases()...)
	if err := w.emit(); err != nil {
		return err
	}
	f.funcs = append(f.funcs, w.buf.String())
	return nil
}

// Bytes formats and returns the generated file.
func (f *File) Bytes() ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by loom. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", f.pkg.Name)
	b.WriteString(f.imports.render())
	for _, fn := range f.funcs {
		b.WriteString("\n")
		b.WriteString(fn)
	}
	src := b.String()
	out, err := format.Source([]byte(src))
	if err != nil {
		return []byte(src), fmt.Errorf("loom: internal error: generated code does not parse: %w", err)
	}
	return out, nil
}

// Empty reports whether no functions were generated.
func (f *File) Empty() bool { return len(f.funcs) == 0 }

// --- import management -----------------------------------------------------

type importSet struct {
	byPath  map[string]string // path -> alias
	byAlias map[string]string // alias -> path
	pkgName map[string]string // path -> package name
}

func newImportSet() *importSet {
	return &importSet{
		byPath:  map[string]string{},
		byAlias: map[string]string{},
		pkgName: map[string]string{},
	}
}

func (s *importSet) add(p *types.Package) string {
	if p == nil || p.Path() == "" {
		return ""
	}
	if alias, ok := s.byPath[p.Path()]; ok {
		return alias
	}
	name := p.Name()
	alias := name
	for i := 2; ; i++ {
		if _, taken := s.byAlias[alias]; !taken && !reservedIdent(alias) {
			break
		}
		alias = name + strconv.Itoa(i)
	}
	s.byPath[p.Path()] = alias
	s.byAlias[alias] = p.Path()
	s.pkgName[p.Path()] = name
	return alias
}

func (s *importSet) aliases() []string {
	out := make([]string, 0, len(s.byAlias))
	for a := range s.byAlias {
		out = append(out, a)
	}
	sort.Strings(out)
	return out
}

func (s *importSet) render() string {
	if len(s.byPath) == 0 {
		return ""
	}
	paths := make([]string, 0, len(s.byPath))
	for p := range s.byPath {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	var std, other []string
	for _, p := range paths {
		if isStdlib(p) {
			std = append(std, p)
		} else {
			other = append(other, p)
		}
	}

	var b strings.Builder
	b.WriteString("import (\n")
	for _, p := range std {
		s.writeImport(&b, p)
	}
	if len(std) > 0 && len(other) > 0 {
		b.WriteString("\n")
	}
	for _, p := range other {
		s.writeImport(&b, p)
	}
	b.WriteString(")\n")
	return b.String()
}

func (s *importSet) writeImport(b *strings.Builder, p string) {
	alias := s.byPath[p]
	if alias == s.pkgName[p] {
		fmt.Fprintf(b, "\t%q\n", p)
	} else {
		fmt.Fprintf(b, "\t%s %q\n", alias, p)
	}
}

// isStdlib reports whether an import path is a standard library package, which
// has no dot in its first path element.
func isStdlib(path string) bool {
	first := path
	if i := strings.IndexByte(path, '/'); i >= 0 {
		first = path[:i]
	}
	return !strings.Contains(first, ".")
}

// --- collection ------------------------------------------------------------

// collect walks a plan and registers every package the generated code will
// reference. It must run for all graphs before any graph is emitted, so that
// import aliases are known before local variable names are allocated.
func (f *File) collect(g *model.Graph, plan *resolve.Plan) {
	f.imports.add(f.opts.LoomPkg)
	f.registerType(g.Target)
	if g.WithCtx {
		f.registerType(f.opts.Context)
	}
	if plan.HasCleanup() {
		f.registerType(f.opts.Context)
		if plan.HasError() && f.opts.ErrorsPkg != nil {
			f.imports.add(f.opts.ErrorsPkg)
		}
	}
	for _, s := range plan.Steps {
		p := s.Provider
		if p == nil {
			continue
		}
		switch p.Kind {
		case model.KindConstructor:
			if p.RefPkg != nil && p.RefPkg != f.pkg.Types {
				f.imports.add(p.RefPkg)
			}
			for _, a := range p.TypeArgs {
				f.registerType(a)
			}
		case model.KindValue:
			f.registerExpr(p.Expr, p.ExprPkg.TypesInfo)
		}
	}
}

func (f *File) registerExpr(e ast.Expr, info *types.Info) {
	ast.Inspect(e, func(n ast.Node) bool {
		switch v := n.(type) {
		case *ast.Ident:
			if obj := info.ObjectOf(v); obj != nil {
				if pn, ok := obj.(*types.PkgName); ok {
					f.imports.add(pn.Imported())
				}
			}
		case nil:
			return false
		}
		if e, ok := n.(ast.Expr); ok {
			if tv, ok := info.Types[e]; ok && tv.IsType() {
				f.registerType(tv.Type)
			}
		}
		return true
	})
}

func (f *File) registerType(t types.Type) {
	seen := map[types.Type]bool{}
	var walk func(types.Type)
	walk = func(t types.Type) {
		if t == nil || seen[t] {
			return
		}
		seen[t] = true
		switch u := types.Unalias(t).(type) {
		case *types.Named:
			if obj := u.Obj(); obj != nil && obj.Pkg() != nil && obj.Pkg() != f.pkg.Types {
				f.imports.add(obj.Pkg())
			}
			args := u.TypeArgs()
			for i := 0; i < args.Len(); i++ {
				walk(args.At(i))
			}
		case *types.Pointer:
			walk(u.Elem())
		case *types.Slice:
			walk(u.Elem())
		case *types.Array:
			walk(u.Elem())
		case *types.Map:
			walk(u.Key())
			walk(u.Elem())
		case *types.Chan:
			walk(u.Elem())
		case *types.Signature:
			if u.Params() != nil {
				walk(u.Params())
			}
			if u.Results() != nil {
				walk(u.Results())
			}
		case *types.Tuple:
			for i := 0; i < u.Len(); i++ {
				walk(u.At(i).Type())
			}
		case *types.Struct:
			for i := 0; i < u.NumFields(); i++ {
				walk(u.Field(i).Type())
			}
		case *types.Interface:
			for i := 0; i < u.NumMethods(); i++ {
				walk(u.Method(i).Type())
			}
		}
	}
	walk(t)
}

// --- graph emission --------------------------------------------------------

type graphWriter struct {
	f        *File
	g        *model.Graph
	plan     *resolve.Plan
	buf      bytes.Buffer
	names    *namer
	varNames map[*resolve.Step]string
}

func (w *graphWriter) typeString(t types.Type) string {
	return types.TypeString(t, w.qualifier)
}

func (w *graphWriter) qualifier(p *types.Package) string {
	if p == nil || p == w.f.pkg.Types {
		return ""
	}
	return w.f.imports.add(p)
}

func (w *graphWriter) loomAlias() string { return w.f.imports.add(w.f.opts.LoomPkg) }

func (w *graphWriter) emit() error {
	target := w.typeString(w.g.Target)
	fmt.Fprintf(&w.buf, "// %s builds %s from the graph declared by %s.\n",
		w.g.Name, target, w.g.VarName)
	if w.g.WithCtx {
		fmt.Fprintf(&w.buf, "func %s(ctx %s) (%s, %s, error) {\n",
			w.g.Name, w.typeString(w.f.opts.Context), target, w.typeString(w.f.opts.LifecyclePtr))
	} else {
		fmt.Fprintf(&w.buf, "func %s() (%s, %s, error) {\n",
			w.g.Name, target, w.typeString(w.f.opts.LifecyclePtr))
	}
	fmt.Fprintf(&w.buf, "\tlifecycle := %s.NewLifecycle()\n", w.loomAlias())
	if len(w.plan.Steps) > 0 {
		w.buf.WriteString("\n")
	}

	for i, s := range w.plan.Steps {
		if i > 0 {
			w.buf.WriteString("\n")
		}
		if err := w.emitStep(s); err != nil {
			return err
		}
	}

	root := w.varOf(w.plan.Root)
	if len(w.plan.Steps) > 0 {
		w.buf.WriteString("\n")
	}
	fmt.Fprintf(&w.buf, "\treturn %s, lifecycle, nil\n}\n", root)
	return nil
}

// varOf returns the variable holding a step's value, allocating a name for
// provider steps on first use. Framework steps have fixed names.
func (w *graphWriter) varOf(s *resolve.Step) string {
	switch s.Kind {
	case resolve.StepLifecycle:
		return "lifecycle"
	case resolve.StepContext:
		return "ctx"
	}
	if name, ok := w.varNames[s]; ok {
		return name
	}
	name := w.alloc(s.Provider)
	w.varNames[s] = name
	return name
}

func (w *graphWriter) emitStep(s *resolve.Step) error {
	switch s.Kind {
	case resolve.StepLifecycle:
		w.varNames[s] = "lifecycle"
		return nil
	case resolve.StepContext:
		w.varNames[s] = "ctx"
		return nil
	}

	p := s.Provider
	args := make([]string, len(s.Deps))
	for i, d := range s.Deps {
		args[i] = w.varOf(d)
	}
	name := w.varOf(s)

	switch p.Kind {
	case model.KindValue:
		expr, err := w.expr(p.Expr, p.ExprPkg)
		if err != nil {
			return err
		}
		fmt.Fprintf(&w.buf, "\t%s := %s\n", name, expr)
		return nil

	case model.KindConstructor:
		call := w.ref(p) + "(" + strings.Join(args, ", ") + ")"
		cleanup := p.Cleanup != nil
		cleanupName := ""
		if cleanup {
			cleanupName = w.names.alloc(name + "Cleanup")
		}
		switch {
		case cleanup && p.HasError:
			fmt.Fprintf(&w.buf, "\t%s, %s, err := %s\n", name, cleanupName, call)
			w.emitErrReturn()
			w.emitAddCleanup(cleanupName, p)
		case cleanup:
			fmt.Fprintf(&w.buf, "\t%s, %s := %s\n", name, cleanupName, call)
			w.emitAddCleanup(cleanupName, p)
		case p.HasError:
			fmt.Fprintf(&w.buf, "\t%s, err := %s\n", name, call)
			w.emitErrReturn()
		default:
			fmt.Fprintf(&w.buf, "\t%s := %s\n", name, call)
		}
		return nil
	}
	return fmt.Errorf("loom: internal error: unknown provider kind")
}

func (w *graphWriter) emitErrReturn() {
	zero := w.zeroValue()
	if w.plan.HasCleanup() && w.f.opts.ErrorsPkg != nil {
		fmt.Fprintf(&w.buf, "\tif err != nil {\n\t\treturn %s, nil, %s.Join(err, lifecycle.Rollback(%s))\n\t}\n",
			zero, w.imports().add(w.f.opts.ErrorsPkg), w.ctxArg())
		return
	}
	fmt.Fprintf(&w.buf, "\tif err != nil {\n\t\treturn %s, nil, err\n\t}\n", zero)
}

// zeroValue is the zero value of the graph target, suitable for error returns
// from a function whose first result may not be nilable.
func (w *graphWriter) zeroValue() string {
	if nilable(w.g.Target) {
		return "nil"
	}
	return "*new(" + w.typeString(w.g.Target) + ")"
}

func (w *graphWriter) emitAddCleanup(name string, p *model.Provider) {
	if w.cleanupAssignable(p.Cleanup) {
		fmt.Fprintf(&w.buf, "\tlifecycle.AddCleanup(%s)\n", name)
		return
	}
	sig, _ := types.Unalias(p.Cleanup).Underlying().(*types.Signature)
	ctxType := w.typeString(w.f.opts.Context)
	var body string
	switch {
	case sig.Params().Len() == 1 && sig.Results().Len() == 1:
		body = fmt.Sprintf("return %s(ctx)", name)
	case sig.Params().Len() == 1:
		body = fmt.Sprintf("%s(ctx)\n\t\treturn nil", name)
	case sig.Results().Len() == 1:
		body = fmt.Sprintf("return %s()", name)
	default:
		body = fmt.Sprintf("%s()\n\t\treturn nil", name)
	}
	fmt.Fprintf(&w.buf, "\tlifecycle.AddCleanup(func(ctx %s) error {\n\t\t%s\n\t})\n", ctxType, body)
}

func (w *graphWriter) cleanupAssignable(t types.Type) bool {
	if w.f.opts.Cleanup == nil {
		return false
	}
	return types.AssignableTo(t, w.f.opts.Cleanup)
}

func (w *graphWriter) ctxArg() string {
	if w.g.WithCtx {
		return "ctx"
	}
	return w.imports().add(pkgOf(w.f.opts.Context)) + ".Background()"
}

func (w *graphWriter) imports() *importSet { return w.f.imports }

func (w *graphWriter) ref(p *model.Provider) string {
	name := p.RefName
	if p.RefPkg != nil && p.RefPkg != w.f.pkg.Types {
		name = w.imports().add(p.RefPkg) + "." + name
	}
	if len(p.TypeArgs) > 0 {
		parts := make([]string, len(p.TypeArgs))
		for i, a := range p.TypeArgs {
			parts[i] = w.typeString(a)
		}
		name += "[" + strings.Join(parts, ", ") + "]"
	}
	return name
}

func (w *graphWriter) alloc(p *model.Provider) string {
	base := typeVarName(p.Output)
	if base == "" {
		base = identFromProvider(p.Name)
	}
	return w.names.alloc(base)
}

// --- expression printing for loom.Supply -----------------------------------

func (w *graphWriter) expr(e ast.Expr, pkg *packages.Package) (string, error) {
	info := pkg.TypesInfo
	switch v := e.(type) {
	case *ast.ParenExpr:
		s, err := w.expr(v.X, pkg)
		return "(" + s + ")", err
	case *ast.Ident:
		obj := info.ObjectOf(v)
		if obj == nil || obj.Pkg() == nil {
			return v.Name, nil
		}
		if pn, ok := obj.(*types.PkgName); ok {
			return w.imports().add(pn.Imported()), nil
		}
		if obj.Pkg() != w.f.pkg.Types {
			return "", fmt.Errorf("loom.Supply: expression references %s from another package; use a package-qualified name", v.Name)
		}
		return v.Name, nil
	case *ast.SelectorExpr:
		x, err := w.expr(v.X, pkg)
		if err != nil {
			return "", err
		}
		return x + "." + v.Sel.Name, nil
	case *ast.BasicLit:
		return v.Value, nil
	case *ast.CompositeLit:
		var b strings.Builder
		if v.Type != nil {
			typ, err := w.exprOrType(v.Type, pkg)
			if err != nil {
				return "", err
			}
			b.WriteString(typ)
		}
		b.WriteString("{")
		for i, el := range v.Elts {
			if i > 0 {
				b.WriteString(", ")
			}
			s, err := w.expr(el, pkg)
			if err != nil {
				return "", err
			}
			b.WriteString(s)
		}
		b.WriteString("}")
		return b.String(), nil
	case *ast.KeyValueExpr:
		k, err := w.expr(v.Key, pkg)
		if err != nil {
			return "", err
		}
		val, err := w.expr(v.Value, pkg)
		if err != nil {
			return "", err
		}
		return k + ": " + val, nil
	case *ast.CallExpr:
		fn, err := w.exprOrType(v.Fun, pkg)
		if err != nil {
			return "", err
		}
		parts := make([]string, len(v.Args))
		for i, a := range v.Args {
			s, err := w.expr(a, pkg)
			if err != nil {
				return "", err
			}
			parts[i] = s
		}
		ellipsis := ""
		if v.Ellipsis.IsValid() {
			ellipsis = "..."
		}
		return fn + "(" + strings.Join(parts, ", ") + ellipsis + ")", nil
	case *ast.IndexExpr:
		x, err := w.expr(v.X, pkg)
		if err != nil {
			return "", err
		}
		idx, err := w.exprOrType(v.Index, pkg)
		if err != nil {
			return "", err
		}
		return x + "[" + idx + "]", nil
	case *ast.IndexListExpr:
		x, err := w.expr(v.X, pkg)
		if err != nil {
			return "", err
		}
		parts := make([]string, len(v.Indices))
		for i, idx := range v.Indices {
			s, err := w.exprOrType(idx, pkg)
			if err != nil {
				return "", err
			}
			parts[i] = s
		}
		return x + "[" + strings.Join(parts, ", ") + "]", nil
	case *ast.UnaryExpr:
		x, err := w.expr(v.X, pkg)
		return v.Op.String() + x, err
	case *ast.BinaryExpr:
		lhs, err := w.expr(v.X, pkg)
		if err != nil {
			return "", err
		}
		rhs, err := w.expr(v.Y, pkg)
		if err != nil {
			return "", err
		}
		return lhs + " " + v.Op.String() + " " + rhs, nil
	case *ast.StarExpr:
		x, err := w.exprOrType(v.X, pkg)
		return "*" + x, err
	case *ast.ArrayType, *ast.MapType, *ast.StructType, *ast.InterfaceType, *ast.ChanType, *ast.FuncType:
		return w.typeString(info.TypeOf(e)), nil
	default:
		return "", fmt.Errorf("loom.Supply: unsupported expression %T in generated code; assign it to a package-level variable", e)
	}
}

func (w *graphWriter) exprOrType(e ast.Expr, pkg *packages.Package) (string, error) {
	if tv, ok := pkg.TypesInfo.Types[e]; ok && tv.IsType() {
		return w.typeString(tv.Type), nil
	}
	return w.expr(e, pkg)
}

// --- names -----------------------------------------------------------------

type namer struct {
	used map[string]bool
}

func newNamer() *namer { return &namer{used: map[string]bool{}} }

func (n *namer) reserve(names ...string) {
	for _, name := range names {
		n.used[name] = true
	}
}

func (n *namer) alloc(base string) string {
	if !validIdent(base) {
		base = "value"
	}
	if types.Universe.Lookup(base) != nil {
		base += "Value"
	}
	name := base
	for i := 2; n.used[name]; i++ {
		name = base + strconv.Itoa(i)
	}
	n.used[name] = true
	return name
}

func reservedIdent(name string) bool {
	return types.Universe.Lookup(name) != nil || token.IsKeyword(name)
}

func validIdent(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		if r == '_' || unicode.IsLetter(r) || (i > 0 && unicode.IsDigit(r)) {
			continue
		}
		return false
	}
	return true
}

// typeVarName derives a readable local variable name from a type:
// *Config -> config, Repository[User] -> userRepository.
func typeVarName(t types.Type) string {
	t = types.Unalias(t)
	if ptr, ok := t.(*types.Pointer); ok {
		t = types.Unalias(ptr.Elem())
	}
	switch u := t.(type) {
	case *types.Named:
		base := lowerFirst(u.Obj().Name())
		var prefix string
		args := u.TypeArgs()
		for i := 0; i < args.Len(); i++ {
			prefix += typeBaseName(args.At(i))
		}
		if prefix == "" {
			return base
		}
		return prefix + upperFirst(base)
	case *types.Slice:
		return typeBaseName(u.Elem()) + "List"
	case *types.Map:
		return typeBaseName(u.Elem()) + "Map"
	case *types.Basic:
		return lowerFirst(u.Name())
	}
	return ""
}

func typeBaseName(t types.Type) string {
	t = types.Unalias(t)
	if ptr, ok := t.(*types.Pointer); ok {
		t = types.Unalias(ptr.Elem())
	}
	switch u := t.(type) {
	case *types.Named:
		return lowerFirst(u.Obj().Name())
	case *types.Basic:
		return lowerFirst(u.Name())
	}
	return ""
}

// identFromProvider turns a constructor name into a variable base name by
// stripping common prefixes: NewUserService -> userService, provideFoo -> foo.
func identFromProvider(name string) string {
	for _, prefix := range []string{"New", "Provide", "Make", "Create"} {
		if !strings.HasPrefix(name, prefix) || len(name) == len(prefix) {
			continue
		}
		rest := name[len(prefix):]
		if r, _ := utf8.DecodeRuneInString(rest); unicode.IsUpper(r) {
			return lowerFirst(rest)
		}
	}
	return lowerFirst(name)
}

// lowerFirst lowercases an identifier's leading word while preserving
// initialisms: Config -> config, DB -> db, HTTPServer -> httpServer.
func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	runes := []rune(s)
	n := 0
	for n < len(runes) && unicode.IsUpper(runes[n]) {
		n++
	}
	switch {
	case n == 0:
		return s
	case n == len(runes):
		return strings.ToLower(s)
	case n > 1:
		n-- // keep the last uppercase letter; it starts the next word
	}
	return strings.ToLower(string(runes[:n])) + string(runes[n:])
}

func upperFirst(s string) string {
	if s == "" {
		return s
	}
	r, size := utf8.DecodeRuneInString(s)
	return string(unicode.ToUpper(r)) + s[size:]
}

func pkgOf(t types.Type) *types.Package {
	if t == nil {
		return nil
	}
	if named, ok := types.Unalias(t).(*types.Named); ok {
		return named.Obj().Pkg()
	}
	return nil
}

// nilable reports whether the zero value of t is nil.
func nilable(t types.Type) bool {
	if t == nil {
		return true
	}
	switch types.Unalias(t).Underlying().(type) {
	case *types.Pointer, *types.Interface, *types.Slice, *types.Map, *types.Chan, *types.Signature:
		return true
	}
	return false
}
