// Code generated by loom. DO NOT EDIT.

package full

import (
	"context"
	"errors"

	"github.com/Xwudao/loom"
)

// InitApp builds *Application from the graph declared by AppGraph.
func InitApp(ctx context.Context) (*Application, *loom.Lifecycle, error) {
	lifecycle := loom.NewLifecycle()

	appName := AppName("full")

	config := NewConfig()

	logger := NewLogger(config)

	database, databaseCleanup, err := NewDatabase(config)
	if err != nil {
		return nil, nil, errors.Join(err, lifecycle.Rollback(ctx))
	}
	lifecycle.AddCleanup(databaseCleanup)

	userRepository := NewRepository[User](database)

	userStore := NewUserStore(userRepository, logger)

	userService := NewUserService(userStore, logger)

	httpServer := NewHTTPServer(lifecycle, config, logger, userService)

	articleRepository := NewRepository[Article](database)

	articleService := NewArticleService(articleRepository, logger)

	application := NewApplication(appName, config, logger, database, httpServer, userService, articleService)

	return application, lifecycle, nil
}

// InitWorker builds *Worker from the graph declared by WorkerGraph.
func InitWorker() (*Worker, *loom.Lifecycle, error) {
	lifecycle := loom.NewLifecycle()

	config := NewConfig()

	database, databaseCleanup, err := NewDatabase(config)
	if err != nil {
		return nil, nil, errors.Join(err, lifecycle.Rollback(context.Background()))
	}
	lifecycle.AddCleanup(databaseCleanup)

	logger := NewLogger(config)

	worker := NewWorker(database, logger)

	return worker, lifecycle, nil
}
