// Code generated by loom. DO NOT EDIT.

package rollback

import (
	"context"
	"errors"

	"github.com/Xwudao/loom"
)

// Keep AppGraph referenced: it is a compile-time graph declaration.
var _ = AppGraph

// InitApp builds *App from the graph declared by AppGraph.
func InitApp() (*App, *loom.Lifecycle, error) {
	lifecycle := loom.NewLifecycle()

	config := NewConfig()

	db, dbCleanup, err := NewDB(config)
	if err != nil {
		return nil, nil, errors.Join(err, lifecycle.Rollback(context.Background()))
	}
	lifecycle.AddCleanup(dbCleanup)

	cache, cacheCleanup, err := NewCache()
	if err != nil {
		return nil, nil, errors.Join(err, lifecycle.Rollback(context.Background()))
	}
	lifecycle.AddCleanup(func(ctx context.Context) error {
		cacheCleanup()
		return nil
	})

	server, err := NewServer(db, cache)
	if err != nil {
		return nil, nil, errors.Join(err, lifecycle.Rollback(context.Background()))
	}

	app := NewApp(server)

	return app, lifecycle, nil
}
