// Code generated by loom. DO NOT EDIT.

package lifecycle

import (
	"context"
	"errors"

	"github.com/Xwudao/loom"
)

// InitApp builds *App from the graph declared by AppGraph.
func InitApp() (*App, *loom.Lifecycle, error) {
	lifecycle := loom.NewLifecycle()

	config := NewConfig()

	db, dbCleanup, err := NewDB(config)
	if err != nil {
		return nil, nil, errors.Join(err, lifecycle.Rollback(context.Background()))
	}
	lifecycle.AddCleanup(dbCleanup)

	cache, cacheCleanup := NewCache()
	lifecycle.AddCleanup(func(ctx context.Context) error {
		cacheCleanup()
		return nil
	})

	server := NewServer(lifecycle, db, cache)

	app := NewApp(server)

	return app, lifecycle, nil
}
