// Code generated by loom. DO NOT EDIT.

package iface

import (
	"github.com/Xwudao/loom"
)

// Keep AppGraph referenced: it is a compile-time graph declaration.
var _ = AppGraph

// InitApp builds *App from the graph declared by AppGraph.
func InitApp() (*App, *loom.Lifecycle, error) {
	lifecycle := loom.NewLifecycle()

	db := NewDB()

	userStore := NewUserStore(db)

	userService := NewUserService(userStore)

	app := NewApp(userService)

	return app, lifecycle, nil
}
