// Code generated by loom. DO NOT EDIT.

package generic

import (
	"github.com/Xwudao/loom"
)

// Keep AppGraph referenced: it is a compile-time graph declaration.
var _ = AppGraph

// InitApp builds *App from the graph declared by AppGraph.
func InitApp() (*App, *loom.Lifecycle, error) {
	lifecycle := loom.NewLifecycle()

	db := NewDB()

	userRepository := NewRepository[User](db)

	userService := NewUserService(userRepository)

	articleRepository := NewRepository[Article](db)

	articleService := NewArticleService(articleRepository)

	app := NewApp(userService, articleService)

	return app, lifecycle, nil
}
