// Code generated by loom. DO NOT EDIT.

package basic

import (
	"github.com/Xwudao/loom"
)

// InitApp builds *App from the graph declared by AppGraph.
func InitApp() (*App, *loom.Lifecycle, error) {
	lifecycle := loom.NewLifecycle()

	config := NewConfig()

	db := NewDB(config)

	repository := NewRepository(db)

	service := NewService(repository)

	app := NewApp(service)

	return app, lifecycle, nil
}
